name: Build & Tag & Push
on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Create Tag & Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version_bump.outputs.new_tag }}
    steps:
      - uses: actions/checkout@master
      - id: version_bump
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{steps.version_bump.outputs.new_tag}}
          release_name: Release ${{steps.version_bump.outputs.new_tag}}

  vault:
    name: Vault Builder
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@master
      - name: Vault Builder
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: caladreas/jx-builder-vault
          tags: latest,${{needs.tag.outputs.tag}}
          path: vault

  gvmmvnj11:
    name: GraalVM Maven JDK11 Builder
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@master
      - name: Build & Tag & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: caladreas/jx-builder-graalvm-maven-jdk11
          tags: latest,${{needs.tag.outputs.tag}}
          path: graalvm-maven-jdk11

  gvmmvnj8:
    name: GraalVM Maven JDK8 Builder
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@master
      - name: Build & Tag & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: caladreas/jx-builder-graalvm-maven-jdk8
          tags: latest,${{needs.tag.outputs.tag}}
          path: graalvm-maven-jdk8

  go14:
    name: Go 14 Builder
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@master
      - name: Build & Tag & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: caladreas/jx-builder-go14
          tags: latest,${{needs.tag.outputs.tag}}
          path: go-14

  nancygo:
    name: Sonatype Nancy for Go Builder
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@master
      - name: Build & Tag & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: caladreas/jx-builder-nancy-go
          tags: latest,${{needs.tag.outputs.tag}}
          path: sonatype-nancy-go

  anchore:
    name: Anchore CLI
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - uses: actions/checkout@master
      - name: Build & Tag & Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: caladreas/jx-builder-anchore
          tags: latest,${{needs.tag.outputs.tag}}
          path: anchore